### PR TITLE
Arrow function removed as it was breaking argument object context

### PR DESCRIPTION
**Pull request by sumit6b**

### CODE REVIEW

**Comment by anarchicknight** [comment]
Thanks - this was reported earlier by another user.

I will be able to take a look at the PR tonight when I get home from work. If it all works OK in various scenarios I will merge in.

The next major release of the module will go back to using arrow functions and change how the parameters are passed in (breaking change so new major version)

**Comment by anarchicknight** [comment]
can you also bump the package version to 2.1.2 please?

**Comment by sumit6b** [comment]
Sure

**Comment by anarchicknight** [comment]
merged - thank you.

Also just published to npm

**Pull request merged**
